### ISSUE TITLE
fit_ssm does not produce a foieGras object.

### ISSUE THREAD

**Issue by ryanreisinger** [ianjonsen/foieGras#1]
The object returned by `fit_ssm` is not a `foieGras` object, so the print and plot methods can't be called on it.

**Comment by ianjonsen** [comment]
Thanks, Ryan. 

`fit_ssm` produces a compound `tibble` as output, even when fitting to a single track. The `foieGras` class is appended to each `ssm` fit object, rather than the whole `tibble`. So to use the print and plot methods, you need to call the individual fit objects:

`fit <- fit_ssm(data, time.step = 6)`

`fit$ssm[[1]]` - for summary print

`plot(fit$ssm[[1]])` - and so on for fits to multiple individuals...

Help file has been updated to more clearly demonstrate this.

cheers, ian

**Comment by ryanreisinger** [comment]
Ah, right! Thanks, Ian.

R
