### ISSUE TITLE
duplicated date-time policy

### ISSUE THREAD

**Issue by mdsumner** [ianjonsen/foieGras#4]
I started to compare some trip stuff with foieGras and ran into the ole duplicated times thing in the ellie data  - what do you generally do about that? What happens with dividing by zero durations and so forth? I noticed long ago that argosfilter just fudges over it with an epsilon but I consider that a mistake.  ??

**Comment by ianjonsen** [comment]
yeah, that's a good, old chestnut. prefilter() currently flags subsequent observations with the same time to be ignored by the SSM, otherwise you run into estimation issues with the process error variances - multiple quantum states, dividing by 0 time, choose your poison... Still a fudge but there's no info to determine which is the most likely - maybe in the more detailed CLS Argos files but most people have dropped all those extra details by the time they come to fitting a model. I noticed that the crawl folks recommend adding small time increments to each duplicate but this also doesn't seem right

**Comment by mdsumner** [comment]
Ok so you effectively remove them, that's  good
